"""
Django settings for tubeflix project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv # <-- NOVA LINHA: Importa load_dotenv

# Carrega as variáveis de ambiente do arquivo .env
# Certifique-se de que o arquivo .env está na raiz do seu projeto
load_dotenv() # <-- NOVA LINHA: Carrega as variáveis de ambiente


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Lendo a SECRET_KEY das variáveis de ambiente para segurança
# O segundo argumento é uma chave de fallback (APENAS para desenvolvimento, NUNCA em produção real)
SECRET_KEY = os.getenv('SECRET_KEY', 'default-insecure-key-for-dev-only-change-this-for-real-projects')

# SECURITY WARNING: don't run with debug turned on in production!
# Lendo DEBUG das variáveis de ambiente. Converte '1' para True e '0' para False.
DEBUG = os.getenv('DEBUG', '0') == '1'

# Lendo ALLOWED_HOSTS das variáveis de ambiente, separando por vírgula
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hub',
    'videos',
    'users',
    'comments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tubeflix.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tubeflix.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# MUDANÇA CRÍTICA AQUI: Usando PostgreSQL com variáveis de ambiente do Docker Compose
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql', # Define o engine para PostgreSQL
        'NAME': os.getenv('POSTGRES_DB'),         # Nome do BD, lido do .env
        'USER': os.getenv('POSTGRES_USER'),       # Usuário do BD, lido do .env
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'), # Senha do BD, lida do .env
        'HOST': os.getenv('POSTGRES_HOST'),       # Host do BD, lido do .env (será 'db' por causa do docker-compose.yml)
        'PORT': os.getenv('POSTGRES_PORT'),       # Porta do BD, lida do .env
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# STATIC_ROOT = BASE_DIR / 'staticfiles' # Descomente e configure para produção
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/videos/profile/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'